# gen_version.ps1 — генерирует version_auto.h из Git
# Запуск в Pre-Build: powershell -ExecutionPolicy Bypass -File "$(ProjectDir)\gen_version.ps1"
$ErrorActionPreference = "Stop"

function Write-Header-Atomic($path, $text) {
    $tmp = "$path.tmp"
    # CRLF нормализация
    $normalized = $text -replace "(`r)?`n","`r`n"
    # UTF-8 WITH BOM — для предсказуемой обработки rc.exe
    $enc = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($tmp, $normalized + "`r`n", $enc)
    if (Test-Path $path) { Remove-Item -Force $path }
    Move-Item -Force $tmp $path
}

# Пытаемся получить данные из git, но не падаем, если git недоступен
$describe = ""; $sha = "unknown"; $dirty = 0
try {
    $describe = (git describe --tags --long --abbrev=7 --dirty --always).Trim()
    $sha = (git rev-parse --short=7 HEAD).Trim()
    $status = (git status --porcelain)
    if ($status -and $status.Length -gt 0) { $dirty = 1 }
} catch {
    $describe = ""
    $sha = "unknown"
    $dirty = 0
}

# Значения по умолчанию
$major = 1; $minor = 0; $patch = 0; $build = 0
$versionStr = "1.0.0.0"

# Разбор git describe:
#   vX.Y.Z-N-gHASH[-dirty]  => X,Y,Z и build=N
#   vX.Y.Z                  => build=0
#   (иначе)                 => 0.1.0.(rev-count) или 1.0.0.0 если git недоступен
if ($describe -match "^v(\d+)\.(\d+)\.(\d+)-(\d+)-g([0-9a-fA-F]+)(-dirty)?$") {
    $major = [int]$matches[1]
    $minor = [int]$matches[2]
    $patch = [int]$matches[3]
    $build = [int]$matches[4]
    $sha = $matches[5]
    if ($matches[6]) { $dirty = 1 }
    $versionStr = "$major.$minor.$patch.$build"
}
elseif ($describe -match "^v(\d+)\.(\d+)\.(\d+)$") {
    $major = [int]$matches[1]
    $minor = [int]$matches[2]
    $patch = [int]$matches[3]
    $build = 0
    $versionStr = "$major.$minor.$patch.$build"
}
elseif ($describe) {
    try {
        $build = [int](git rev-list --count HEAD)
        # Простейшая «базовая» версия, когда тегов ещё нет
        $major = 0; $minor = 1; $patch = 0
        $versionStr = "$major.$minor.$patch.$build"
    } catch {
        $build = 0
        $versionStr = "1.0.0.0"
    }
}

$gitShaStr = $sha
if ($dirty -eq 1 -and $sha -ne "unknown") { $gitShaStr = "$sha-dirty" }
$ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

# Содержимое заголовка — строго RC/C совместимые макросы
$hdr = @"
// Auto-generated by gen_version.ps1. Do not edit manually.
#ifndef VCF_LISTER_VERSION_AUTO_H
#define VCF_LISTER_VERSION_AUTO_H

#define VCF_LISTER_VER_MAJOR $major
#define VCF_LISTER_VER_MINOR $minor
#define VCF_LISTER_VER_PATCH $patch
#define VCF_LISTER_VER_BUILD $build

// Для RC: запятая-разделённые значения и wide-строки
#define VCF_LISTER_FILEVER        $major,$minor,$patch,$build
#define VCF_LISTER_PRODUCTVER     $major,$minor,$patch,$build
#define VCF_LISTER_STRFILEVER     L"$versionStr"
#define VCF_LISTER_STRPRODUCTVER  L"$versionStr"

#define VCF_LISTER_VERSION_STR           "$versionStr"
#define VCF_LISTER_GIT_SHA               "$gitShaStr"
#define VCF_LISTER_BUILD_TIMESTAMP       "$ts"
#define VCF_LISTER_GIT_SHA_WSTR          L"$gitShaStr"
#define VCF_LISTER_BUILD_TIMESTAMP_WSTR  L"$ts"

#endif // VCF_LISTER_VERSION_AUTO_H
"@

$path = Join-Path $PSScriptRoot "version_auto.h"
Write-Header-Atomic -path $path -text $hdr
Write-Host "version_auto.h generated: $versionStr ($gitShaStr @ $ts)"
