# gen_version.ps1 — генерирует version_auto.h
# ИНКРЕМЕНТ БИЛДА: локальный счётчик в build_state.json (увеличивается КАЖДУЮ сборку)
$ErrorActionPreference = "Stop"

function Write-Header-Atomic($path, $text) {
    $tmp = "$path.tmp"
    $normalized = $text -replace "(`r)?`n","`r`n"
    $enc = New-Object System.Text.UTF8Encoding($true)   # UTF-8 BOM — rc.exe стабильно ест
    [System.IO.File]::WriteAllText($tmp, $normalized + "`r`n", $enc)
    if (Test-Path $path) { Remove-Item -Force $path }
    Move-Item -Force $tmp $path
}

# --- 1) Базовая версия из git-тэга (major.minor.patch) ---
$major = 1; $minor = 0; $patch = 0
try {
    $tag = (git describe --tags --abbrev=0).Trim()   # vX.Y.Z
    if ($tag -match "^v(\d+)\.(\d+)\.(\d+)$") {
        $major = [int]$matches[1]
        $minor = [int]$matches[2]
        $patch = [int]$matches[3]
    }
} catch { }  # если git/tags нет — останется 1.0.0

$base = "$major.$minor.$patch"

# --- 2) Счётчик билда — растёт КАЖДУЮ сборку ---
# Храним base и build, чтобы при смене тэга сбрасывать build в 0
$statePath = Join-Path $PSScriptRoot "build_state.json"
$build = 0
if (Test-Path $statePath) {
    try {
        $st = Get-Content $statePath -Raw | ConvertFrom-Json
        if ($st.base -eq $base) { $build = [int]$st.build + 1 } else { $build = 0 }
    } catch { $build = 0 }
} else {
    $build = 0
}
# Сохраняем новое состояние
@{ base = $base; build = $build } | ConvertTo-Json | Set-Content -Encoding UTF8 $statePath

# --- 3) Git SHA и -dirty (не критично для билда) ---
$sha = "unknown"; $dirty = $false
try {
    $sha = (git rev-parse --short=7 HEAD).Trim()
    $dirty = ((git status --porcelain).Length -gt 0)
} catch { }

$gitShaStr = if ($dirty -and $sha -ne "unknown") { "$sha-dirty" } else { $sha }
$ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

# --- 4) Итоговая строка версии ---
$versionStr = "$base.$build"   # X.Y.Z.build

# --- 5) Пишем заголовок для RC/кода ---
$hdr = @"
// Auto-generated by gen_version.ps1. Do not edit manually.
#ifndef VCF_LISTER_VERSION_AUTO_H
#define VCF_LISTER_VERSION_AUTO_H

#define VCF_LISTER_VER_MAJOR $major
#define VCF_LISTER_VER_MINOR $minor
#define VCF_LISTER_VER_PATCH $patch
#define VCF_LISTER_VER_BUILD $build

#define VCF_LISTER_FILEVER        $major,$minor,$patch,$build
#define VCF_LISTER_PRODUCTVER     $major,$minor,$patch,$build
#define VCF_LISTER_STRFILEVER     L"$versionStr"
#define VCF_LISTER_STRPRODUCTVER  L"$versionStr"

#define VCF_LISTER_VERSION_STR           "$versionStr"
#define VCF_LISTER_GIT_SHA               "$gitShaStr"
#define VCF_LISTER_BUILD_TIMESTAMP       "$ts"
#define VCF_LISTER_GIT_SHA_WSTR          L"$gitShaStr"
#define VCF_LISTER_BUILD_TIMESTAMP_WSTR  L"$ts"

#endif // VCF_LISTER_VERSION_AUTO_H
"@

$path = Join-Path $PSScriptRoot "version_auto.h"
Write-Header-Atomic -path $path -text $hdr
Write-Host "version_auto.h generated: $versionStr ($gitShaStr @ $ts)"
