// Auto-generated by gen_version.ps1. Do not edit manually.
#ifndef VCF_LISTER_VERSION_AUTO_H
#define VCF_LISTER_VERSION_AUTO_H

#define VCF_LISTER_VER_MAJOR 2
#define VCF_LISTER_VER_MINOR 4
#define VCF_LISTER_VER_PATCH 6
#define VCF_LISTER_VER_BUILD 0

#define VCF_LISTER_FILEVER        2,4,6,0
#define VCF_LISTER_PRODUCTVER     2,4,6,0
#define VCF_LISTER_STRFILEVER     L"2.4.6.0"
#define VCF_LISTER_STRPRODUCTVER L"2.4.6.0"

#define VCF_LISTER_VERSION_STR           "2.4.6.0"
#define VCF_LISTER_GIT_SHA               "a26adcc-dirty"
#define VCF_LISTER_BUILD_TIMESTAMP       "2026-07-31T15:08:19Z"
#define VCF_LISTER_GIT_SHA_WSTR          L"a26adcc-dirty"
#define VCF_LISTER_BUILD_TIMESTAMP_WSTR  L"2026-07-31T15:08:19Z"

#endif // VCF_LISTER_VERSION_AUTO_H
