// Auto-generated by gen_version.ps1. Do not edit manually.
#ifndef VCF_LISTER_VERSION_AUTO_H
#define VCF_LISTER_VERSION_AUTO_H

#define VCF_LISTER_VER_MAJOR 2
#define VCF_LISTER_VER_MINOR 1
#define VCF_LISTER_VER_PATCH 0
#define VCF_LISTER_VER_BUILD 0

#define VCF_LISTER_FILEVER        2,1,0,0
#define VCF_LISTER_PRODUCTVER     2,1,0,0
#define VCF_LISTER_STRFILEVER     L"2.1.0.0"
#define VCF_LISTER_STRPRODUCTVER L"2.1.0.0"

#define VCF_LISTER_VERSION_STR           "2.1.0.0"
#define VCF_LISTER_GIT_SHA               "6acc3a3-dirty"
#define VCF_LISTER_BUILD_TIMESTAMP       "2026-07-28T07:39:51Z"
#define VCF_LISTER_GIT_SHA_WSTR          L"6acc3a3-dirty"
#define VCF_LISTER_BUILD_TIMESTAMP_WSTR  L"2026-07-28T07:39:51Z"

#endif // VCF_LISTER_VERSION_AUTO_H
